version: '3.3'

services:
  postgres:
    image: postgres:14.6-alpine
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data:cached
      - ./db/dump/:/docker-entrypoint-initdb.d/
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust

  redis:
    image: redis:6.0.16-alpine
    ports:
      - 6379:6379
    volumes:
      - redis:/var/lib/redis/data:cached


volumes:
  postgres:
  redis:
