version: '3.3'

services:
  postgres:
    image: postgres:14.6-alpine
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data:cached
      - ./db/dump/:/docker-entrypoint-initdb.d/
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust

volumes:
  postgres:
